name: Build "turnip"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        type: string

permissions:
  contents: write

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04

    env:
      BUILD_VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
          sudo apt install -y build-essential flex bison glslang-tools
          sudo apt install -y meson-1.5

      - name: Execute build script
        run: bash ./turnip_builder.sh

      - name: Release "turnip"
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Mainline Turnip Vulkan V${{ inputs.version }}
            Built from: https://github.com/whitebelyash/mesa-unified (turnip/gen8 branch).

            Custom build for Armada OS / Waydroid using MSM/DRM.

            Supported GPUs:
            * Adreno 8XX Family
            * Adreno 7XX Family
            * Adreno 6XX Family

            Notes:
            * Built for Android ARM64
            * Freedreno KMD: MSM
            * Intended for Waydroid using /dev/dri/renderD128
            * TU_DEBUG=sysmem may be used where needed

          tag_name: tu_v${{ inputs.version }}
          name: Mainline Turnip v${{ inputs.version }}

          files: |
            /tmp/mainline-turnip-V${{ inputs.version }}.zip
            /tmp/mainline-turnip-sync-V${{ inputs.version }}.zip
