name: Build Stable Turnip MSM

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        type: string

permissions:
  contents: write

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04

    env:
      BUILD_VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
          sudo apt install -y build-essential flex bison glslang-tools
          sudo apt install -y meson-1.5

      - name: Execute build script
        run: bash ./turnip_builder.sh

      - name: Release Stable Turnip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: stu_v${{ inputs.version }}
          name: Stable Turnip MSM v${{ inputs.version }}

          body: |
            Stable Turnip MSM build for Armada OS / Waydroid.

            Base:
            - Whitebelyash mesa-unified turnip/26.2
            - Mesa 26.2.0
            - Android ARM64
            - Freedreno KMD: MSM/DRM
            - Intended for /dev/dri/renderD128

          files: |
            /tmp/mainline-turnip-V${{ inputs.version }}.zip
